version: '3.1'
services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.production
    container_name: 'server-express'
    environment:
      - DOCKER=true
    ports:
      - 80:80
    command: 'node build/main.js'
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: 'client-react'
    environment:
      - NODE_ENV=production
    ports:
      - 8080:3000
    volumes:
      - ./frontend/react-pomodoro:/usr/src/app
    command: 'npm run start'
