version: '3.1'
services:
  db:
    image: mongo
    container_name: mongo-pomodoro
    command:
      - mongod
    ports:
      - 27017:27017
    volumes:
      - ./db:/data/db
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile
    container_name: 'server-express'
    environment:
      - DOCKER=true
    ports:
      - 80:80
    depends_on:
      - db
  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: 'client-react'
    environment:
      - NODE_ENV=development
    ports:
      - 8080:8080
    volumes:
      - ./frontend/react-pomodoro:/usr/src/app
    command: 'npm run start'
