orbs:
  aws-cli: circleci/aws-cli@1.1.0

jobs:
  frontend-test:
    docker:
      - image: cimg/node:19.8.1
    working_directory: ~/frontend/react-pomodoro
    steps:
      - checkout
      - run:
          name: Install frontend dependencies
          command: npm ci
      - run:
          name: Run frontend tests
          command: |
            if [ $(git diff --name-only HEAD^ HEAD | grep -E '^frontend/react-pomodoro/') ]; then
              npm run test:ci
            else
              circleci-agent step halt
            fi

  backend-test:
    docker:
      - image: cimg/node:19.8.1
    working_directory: ~/backend/express-pomodoro
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: npm ci
      - run:
          name: Run backend tests
          command: |
            if [ "$(git diff --name-only HEAD^ HEAD | grep -E '^backend/express-pomodoro/')" ]; then
              npm run test
            else
              circleci-agent step halt
            fi

  tag:
    docker:
      - image: cimg/base:2021.04
    steps:
      - checkout
      - run: |
          latest_tag=$(git describe --tags --abbrev=0)
          tag_parts=($(echo $latest_tag | tr "." " "))
          patch=$(expr ${tag_parts[2]} + 1)
          version="${tag_parts[0]}.${tag_parts[1]}.${patch}"
          echo "Creating tag ${version}"
          git config --global user.email "${CIRCLE_PROJECT_USERNAME}@users.noreply.github.com"
          git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
          git tag -a "${version}" -m "Version ${version}"
          git push origin "${version}"

  build-deploy:
    docker:
      - image: cimg/node:19.8.1
    working_directory: ~/frontend/react-pomodoro
    steps:
      - checkout
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Build app
          command: npm run build
      - aws-cli/upload:
          bucket: pomodoro-timer.link
          files: frontend/react-pomodoro/build/**
          key_prefix: react-pomodoro/
          overwrite: true

workflows:
  version: 2
  test:
    jobs:
      - frontend-test
      - backend-test
      - tag:
          context: github
          filters:
            branches:
              only: master
      - build-deploy:
          filters:
            tags:
              only: /^v.*/
            branches:
              only: master
