version: 2.1
jobs:
  test-frontend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: cd frontend/react-pomodoro && npm install
      - run:
          name: Run frontend tests
          command: cd frontend/react-pomodoro && npm run test
  test-backend:
    docker:
      - image: circleci/node:14
    steps:
      - checkout
      - run: cd backend/express-pomodoro && npm install
      - run:
          name: Run backend tests
          command: cd backend/express-pomodoro && npm run test
  deploy:
    docker:
      - image: circleci/python:3.8
    steps:
      - checkout
      - run:
          name: Install backend dependencies
          command: cd ./backend/express-pomodoro && npm install
      - run:
          name: Run backend tests
          command: cd ./backend/express-pomodoro && npm run test
workflows:
  version: 2.1
  test:
    jobs:
      - test_frontend:
          filters:
            branches:
              only:
                - master
                - /^pull\/.*$/
      - test_backend:
          filters:
            branches:
              only:
                - master
                - /^pull\/.*$/
