jobs:
  frontend-test:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - run:
          name: Install Git
          command: apk add --no-cache git
      - run:
          name: Install frontend dependencies
          command: |
            cd frontend/react-pomodoro
            npm ci
      - run:
          name: Run frontend tests
          command: |
            if [ $(git diff --name-only HEAD^ HEAD | grep -E '^frontend/react-pomodoro/') ]; then
              cd frontend/react-pomodoro
              npm run test:ci
            else
              circleci-agent step halt
            fi

  backend-test:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - run:
          name: Install Git
          command: apk add --no-cache git
      - run:
          name: Install backend dependencies
          command: |
            cd backend/express-pomodoro
            npm ci
      - run:
          name: Run backend tests
          command: |
            if [ "$(git diff --name-only HEAD^ HEAD | grep -E '^backend/express-pomodoro/')" ]; then
              cd backend/express-pomodoro
              npm run test
            else
              circleci-agent step halt
            fi

workflows:
  version: 2
  test:
    jobs:
      - frontend-test
      - backend-test
