jobs:
  frontend-test:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - run:
          name: Install Git
          command: apk add --no-cache git
      - run:
          name: Install frontend dependencies
          command: |
            cd frontend/react-pomodoro
            npm ci
      - run:
          name: Run frontend tests
          command: |
            if [ $(git diff --name-only HEAD^ HEAD | grep -E '^frontend/react-pomodoro/') ]; then
              cd frontend/react-pomodoro
              npm run test:ci
            else
              circleci-agent step halt
            fi

  backend-test:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - run:
          name: Install Git
          command: apk add --no-cache git
      - run:
          name: Install backend dependencies
          command: |
            cd backend/express-pomodoro
            npm ci
      - run:
          name: Run backend tests
          command: |
            if [ "$(git diff --name-only HEAD^ HEAD | grep -E '^backend/express-pomodoro/')" ]; then
              cd backend/express-pomodoro
              npm run test
            else
              circleci-agent step halt
            fi

  tag:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: .
      - run: |
          version=$(echo ${CIRCLE_PULL_REQUEST_TITLE} | grep -Eo '[0-9]+\.[0-9]+\.[0-9]+')
          changelog=$(git log --pretty=format:"- %s (@%an)" ${CIRCLE_SHA1}..${CIRCLE_BRANCH})
          tag_message="${version}\n\n${changelog}"
          echo "Creating tag ${version} with message:"
          echo "${tag_message}"
          git config --global user.email "${CIRCLE_PROJECT_USERNAME}@users.noreply.github.com"
          git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
          git tag -a ${version} -m "${tag_message}"
          git push origin ${version}

workflows:
  version: 2
  test:
    jobs:
      - frontend-test
      - backend-test
      - tag:
          context: github
          filters:
            branches:
              only: master
