jobs:
  frontend-test:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - run:
          name: Install Git
          command: apk add --no-cache git
      - run:
          name: Install frontend dependencies
          command: |
            cd frontend/react-pomodoro
            npm ci
      - run:
          name: Run frontend tests
          command: |
            if [ $(git diff --name-only HEAD^ HEAD | grep -E '^frontend/react-pomodoro/') ]; then
              cd frontend/react-pomodoro
              npm run test:ci
            else
              circleci-agent step halt
            fi

  backend-test:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - run:
          name: Install Git
          command: apk add --no-cache git
      - run:
          name: Install backend dependencies
          command: |
            cd backend/express-pomodoro
            npm ci
      - run:
          name: Run backend tests
          command: |
            if [ "$(git diff --name-only HEAD^ HEAD | grep -E '^backend/express-pomodoro/')" ]; then
              cd backend/express-pomodoro
              npm run test
            else
              circleci-agent step halt
            fi

  tag:
    docker:
      - image: node:lts-alpine
    steps:
      - checkout
      - run:
          name: Install Git
          command: apk add --no-cache git
      - run: |
          latest_tag=$(git describe --tags --abbrev=0)
          tag_parts=(${latest_tag//v/ })
          patch=$((tag_parts[2]+1))
          version="v${tag_parts[0]}.${tag_parts[1]}.$patch"
          message=$(git log --pretty=format:"- %s (@%an)" ${CIRCLE_SHA1}..${CIRCLE_BRANCH})
          echo "Creating tag ${version} with message:"
          echo "${message}"
          git config --global user.email "${CIRCLE_PROJECT_USERNAME}@users.noreply.github.com"
          git config --global user.name "${CIRCLE_PROJECT_USERNAME}"
          git tag -a ${version} -m "${message}"
          git push origin ${version}

workflows:
  version: 2
  test:
    jobs:
      - frontend-test
      - backend-test
      - tag:
          context: github
          filters:
            branches:
              only: master
